languageCode:           "en"
title:                  "Boosted"
baseURL:                "https://boosted.orange.com"
enableInlineShortcodes: true

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

publishDir:             "_gh_pages"

module:
  mounts:
    - source:           dist
      target:           static/docs/5.0/dist
    - source:           site/assets
      target:           assets
    - source:           site/content
      target:           content
    - source:           site/data
      target:           data
    - source:           site/layouts
      target:           layouts
    - source:           site/static
      target:           static
    - source:           site/static/docs/5.0/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           site/static/docs/5.0/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

      # Boosted mod
    - source:           node_modules/tarteaucitronjs/tarteaucitron.js
      target:           assets/js/vendor/tarteaucitron.js
    - source:           node_modules/tarteaucitronjs/lang
      target:           static/docs/5.0/assets/js/lang

params:
  description:          "Orange Boosted with Bootstrap is a Bootstrap based, Orange branded accessible and ergonomic components library.."
  authors:              "Orange and Boosted contributors"
  social_image_path:    /docs/5.0/assets/brand/orange-social.png
  social_logo_path:     /docs/5.0/assets/brand/orange-social-logo.png

  current_version:      "5.0.0-alpha2"
  current_ruby_version: "5.0.0.alpha1"
  docs_version:         "5.0"
  rfs_version:          "9.0.3"
  repo:                 "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap"
  twitter:              "orange"
  icons:                "https://design.orange.com/icons-libraries/"
  bootstrap:            "https://v5.getbootstrap.com"

  download:
    source:             "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/archive/v5.0.0-alpha2.zip"
    dist:               "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/download/v5.0.0-alpha2/boosted-5.0.0-alpha2-dist.zip"
    dist_examples:      "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/download/v5.0.0-alpha2/boosted-5.0.0-alpha2-examples.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:              "https://cdn.jsdelivr.net/npm/boosted@5.0.0-alpha2/dist/css/boosted.min.css"
    css_hash:         "sha384-7BuBwxbLw5x8O1jfEEtlFq9lbqBmi9a/aWzSSob0V3Xw2xYd4a3fCo127pVNDFhw"
    helvetica:        "https://cdn.jsdelivr.net/npm/boosted@5.0.0-alpha2/dist/css/orange-helvetica.min.css"
    helvetica_hash:   "sha384-2W6Ddgejs+ZLUHWL9OWpfdx8K+DR+e1Muc2B220lXZmOgfxlJhYwD4YAC3AY5Kdx"
    js:               "https://cdn.jsdelivr.net/npm/boosted@5.0.0-alpha2/dist/js/boosted.min.js"
    js_hash:          "sha384-iYvIA3HSz3VXfbm3CMy7/wYkwMUlze27pLneihLNYupgo34fYfCQvdmxY6M537KQ"
    js_bundle:        "https://cdn.jsdelivr.net/npm/boosted@5.0.0-alpha2/dist/js/boosted.bundle.min.js"
    js_bundle_hash:   "sha384-ybSeRKGPCQRfq+levub6c6zk3i5iWrJrFVI0Eumz5ply5psc1trveLjsqXDCUNfW"
    popper:           "https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    popper_hash:      "sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    focus_visible:      "https://cdn.jsdelivr.net/npm/focus-visible@5.1.0/dist/focus-visible.min.js"
    focus_visible_hash: "sha384-xRa5B8rCDfdg0npZcxAh+RXswrbFk3g6dlHVeABeluN8EIwdyljz/LqJgc2R3KNA"
