languageCode:           "en"
title:                  "Boosted"
baseURL:                "https://boosted.orange.com"
enableInlineShortcodes: true

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

publishDir:             "_gh_pages"

module:
  mounts:
    - source:           dist
      target:           static/docs/5.0/dist
    - source:           site/assets
      target:           assets
    - source:           site/content
      target:           content
    - source:           site/data
      target:           data
    - source:           site/layouts
      target:           layouts
    - source:           site/static
      target:           static
    - source:           site/static/docs/5.0/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           site/static/docs/5.0/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

      # Boosted mod
    - source:           node_modules/tarteaucitronjs/tarteaucitron.js
      target:           assets/js/vendor/tarteaucitron.js
    - source:           node_modules/tarteaucitronjs/lang
      target:           static/docs/5.0/assets/js/lang

params:
  description:          "Orange Boosted with Bootstrap is a Bootstrap based, Orange branded accessible and ergonomic components library.."
  authors:              "Orange and Boosted contributors"
  social_image_path:    /docs/5.0/assets/brand/orange-social.png
  social_logo_path:     /docs/5.0/assets/brand/orange-social-logo.png

  current_version:      "5.0.0-beta2"
  current_ruby_version: "5.0.0.beta2"
  docs_version:         "5.0"
  rfs_version:          "9.0.3"
  repo:                 "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap"
  twitter:              "orange"
  icons:                "https://design.orange.com/icons-libraries/"
  bootstrap:            "https://getbootstrap.com"

  download:
    source:             "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/archive/v5.0.0-beta2.zip"
    dist:               "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/download/v5.0.0-beta2/boosted-5.0.0-beta1-dist.zip"
    dist_examples:      "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/download/v5.0.0-beta2/boosted-5.0.0-beta1-examples.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:                "https://cdn.jsdelivr.net/npm/boosted@5.0.0-beta2/dist/css/boosted.min.css"
    css_hash:           "sha384-I+o9IXBrS4QMdE5iTGfWoaGvU4N2v2hJomuDBrMMMNxPoXWpYHPCdb2K8nsWRMoZ"
    css_rtl:            "https://cdn.jsdelivr.net/npm/boosted@5.0.0-beta2/dist/css/boosted.rtl.min.css"
    css_rtl_hash:       "sha384-K2ilmXRtN7qGadxR43tWCc3FeuBbAZhYTehdAyTeDSZ2bWUo0BkLFtotXpo+38td"
    helvetica:          "https://cdn.jsdelivr.net/npm/boosted@5.0.0-beta2/dist/css/orange-helvetica.min.css"
    helvetica_hash:     "sha384-2W6Ddgejs+ZLUHWL9OWpfdx8K+DR+e1Muc2B220lXZmOgfxlJhYwD4YAC3AY5Kdx"
    helvetica_rtl:      "https://cdn.jsdelivr.net/npm/boosted@5.0.0-beta2/dist/css/orange-helvetica.rtl.min.css"
    helvetica_rtl_hash: "sha384-2N+Axfck8AYLrpdsZD0N1m7VB20fwJPh1SzLbOhtlxThb8GEzCaX4uJwMHLxCyxh"
    js:                 "https://cdn.jsdelivr.net/npm/boosted@5.0.0-beta2/dist/js/boosted.min.js"
    js_hash:            "sha384-rFJcUzNS9dZmqBmUPtI69Md+XfMYCBl45fSFhx6aM3tKyS1C8+erUR+1ngZLvCy4"
    js_bundle:          "https://cdn.jsdelivr.net/npm/boosted@5.0.0-beta2/dist/js/boosted.bundle.min.js"
    js_bundle_hash:     "sha384-LfuX/H3NCCkZXu3vAv7z3K59OJXRoDSMVxyOlRhHKrXoO5CzAIhMeiwYmGrbbPIn"
    popper:             "https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"
    popper_hash:        "sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi"
    focus_visible:      "https://cdn.jsdelivr.net/npm/focus-visible@5.1.0/dist/focus-visible.min.js"
    focus_visible_hash: "sha384-xRa5B8rCDfdg0npZcxAh+RXswrbFk3g6dlHVeABeluN8EIwdyljz/LqJgc2R3KNA"
