contact_links:
  - name: Ask a question
    url: https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/discussions/new
    about: Ask and discuss questions with other Boosted community members
