contact_links:
  - name: Ask the community
    url: https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/discussions/new
    about: Ask and discuss questions with other OUDS Web community members.
