name: BrowserStack
on:
  # BrowserStack is for now deactivated when triggered by a push action because always failing
  # push:
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  browserstack:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE }}"
          cache: npm

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm ci

      - name: Run dist
        run: npm run dist

      - name: Run BrowserStack tests
        run: npm run js-test-cloud
        env:
          BROWSER_STACK_ACCESS_KEY: "${{ secrets.BROWSER_STACK_ACCESS_KEY }}"
          BROWSER_STACK_USERNAME: "${{ secrets.BROWSER_STACK_USERNAME }}"
          GITHUB_SHA: "${{ github.sha }}"
