name: cspell

on:
  push:
    branches:
      - main
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  cspell:
    runs-on: ubuntu-latest
    if: "!(contains(github.event.*.labels.*.name, 'skip:ci') || github.actor == 'dependabot[bot]')"

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Run cspell
        uses: streetsidesoftware/cspell-action@v2
        with:
          config: ".cspell.json"
          files: "**/*.md"
          inline: error
          incremental_files_only: false
