name: cspell

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  cspell:
    runs-on: ubuntu-latest

    steps:
      - name: Bail early
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'skip:ci')
        run: exit 0

      - name: Clone repository
        uses: actions/checkout@v3
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip:ci'))

      - name: Run cspell
        uses: streetsidesoftware/cspell-action@v1
        with:
          config: ".cspell.json"
          files: "**/*.md"
          inline: error
          incremental_files_only: false
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip:ci'))
