name: Docs
on:
  push:
    branches:
      - main
    paths:
      - 'js/**'
      - 'scss/**'
      - 'site/**'
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  docs:
    runs-on: ubuntu-latest
    if: "!(contains(github.event.*.labels.*.name, 'skip:ci'))"

    steps:
      - name: Bail early
        run: exit 0
        if: github.actor  == 'dependabot[bot]'

      - name: Clone repository
        uses: actions/checkout@v3
        if: "!(github.actor  == 'dependabot[bot]')"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE }}"
          cache: npm
        if: "!(github.actor  == 'dependabot[bot]')"

      - run: java -version
        if: "!(github.actor  == 'dependabot[bot]')"

      - name: Install npm dependencies
        run: npm ci
        if: "!(github.actor  == 'dependabot[bot]')"

      - name: Build docs
        run: npm run docs-build
        if: "!(github.actor  == 'dependabot[bot]')"

      - name: Validate HTML
        run: npm run docs-vnu
        if: "!(github.actor  == 'dependabot[bot]')"

      - name: Run linkinator
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: _site
          recurse: true
          verbosity: error
          skip: "^(?!http://localhost)"
        if: "!(github.actor  == 'dependabot[bot]')"
