name: Bots
on:
  pull_request:
    types:
      - closed
    branches:
      - v5-dev
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Mattermost message for release
        if: github.event_name == 'release'
        run: |
          echo "{\"text\": \"## Boosted ${{ github.event.release.tag_name }} :tada:\n[![${{ github.actor }}](https://github.com/${{ github.actor }}.png =10) **${{ github.actor }}**](https://github.com/${{ github.actor }}/) ${{ github.event.release.action }} this on ${{ github.event.release.published_at }}\n***\n[Changelog](${{ github.event.release.html_url }}) — [Download (zip)](${{ github.event.release.zipball_url }})\"}" > mattermost.json

      - name: Mattermost message for merged pull request
        if: github.event_name == 'pull_request' && github.event.pull_request.merged
        run: |
          echo "{\"text\": \"[![${{ github.actor }}](https://github.com/${{ github.actor }}.png =10) **${{ github.actor }}**](https://github.com/${{ github.actor }}/) just merged [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) in **v5-dev** — [View diff →](${{ github.event.pull_request.html_url }}/files)\"}" > mattermost.json

      - uses: mattermost/action-mattermost-notify@1.0.0
        if: github.event_name == 'release' || github.event.pull_request.merged
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_USERNAME: "Boosted Release"
          MATTERMOST_ICON: "https://github.com/Orange-OpenSource.png"
