name: Bots
on:
  push:
    branches:
      - chore/tooling
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Mattermost
        run: |
          echo "{\"text\":\"$GITHUB_REPOSITORY → $GITHUB_EVENT_NAME : $GITHUB_REF  // GITHUB_ACTOR :poop:\"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@1.0.0
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_USERNAME: "Boosted Release"
          MATTERMOST_ICON: "https://github.com/Orange-OpenSource.png"
