name: Bots
on:
  push:
    branches:
      - chore/tooling
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create the Mattermost message
        run: |
          echo "{\"text\": \"# Boosted ${{ github.ref }} :tada:\nThis is more text. :tada:\n[Changelog](https://github.com/${{ github.repository }}/releases/tag/${{ github.ref }}) — [Download (zip)](https://github.com/${{ github.repository }}/archive/${{ github.ref }}.zip)\"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@1.0.0
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_USERNAME: "Boosted Release"
          MATTERMOST_ICON: "https://github.com/Orange-OpenSource.png"
