name: Bots
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Mattermost message for release
        if: github.event_name == 'release'
        run: |
          echo "{\"text\": \"## Boosted ${{ github.event.release.tag_name }} :tada:\n[![${{ github.actor }}](https://github.com/${{ github.actor }}.png =10) **${{ github.actor }}**](https://github.com/${{ github.actor }}/) just released ${{ github.event.release.tag_name }}\n***\n[Changelog](${{ github.event.release.html_url }}) — [Download (zip)](${{ github.event.release.zipball_url }})\"}" > mattermost.json

      - name: Notify Mattermost
        uses: mattermost/action-mattermost-notify@1.1.0
        if: github.event_name == 'release'
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_USERNAME: "Boosted Release"
          MATTERMOST_ICON: "https://github.com/Orange-OpenSource.png"
