name: Tests
on:
  push:
    branches:
      - v5-dev
      - "!dependabot/**"
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
    branches:
      - v5-dev
      - "!dependabot/**"
env:
  FORCE_COLOR: 2
  NODE: 14.x

jobs:
  pa11y:
    runs-on: ubuntu-latest

    steps:
      - name: Bail early
        if: github.repository == 'Orange-OpenSource/Orange-Boosted-Bootstrap' && (contains(github.event.*.labels.*.name, 'skip:ci') || contains(github.event.*.labels.*.name, 'skip:pa11y'))
        run: exit 0

      - name: Clone repository
        uses: actions/checkout@v2
        if: failure()

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE }}"
        if: failure()

      - name: Set up npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ env.NODE }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-v${{ env.NODE }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
            ${{ runner.OS }}-node-v${{ env.NODE }}-
        if: failure()

      - name: Install npm dependencies
        run: npm ci
        if: failure()

      - name: Compile dist
        run: npm run dist
        if: failure()

      - name: Test docs
        run: npm run docs-build
        if: failure()

      - name: Run accessibility tests
        run: npm run docs-accessibility
        if: failure()

      - name: Generate HTML accessibility results
        run: npm run docs-pa11y-html
        if: failure()

      - name: Upload accessibility results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: pa11y-ci-results
          path: .pa11y/
