name: Tests
on:
  push:
  pull_request:
    paths:
      - 'js/**'
      - 'scss/**'
      - 'site/**'
    branches:
      - v5-dev
env:
  CI: true

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [10, 12]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version
      - run: java -version

      - name: Set up npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.github/workflows/test.yml') }}
          restore-keys: |
            ${{ runner.OS }}-node-v${{ matrix.node }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.github/workflows/test.yml') }}
            ${{ runner.OS }}-node-v${{ matrix.node }}-

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run accessibility tests
        run: npm run docs-accessibility
        if: matrix.node == 12

      - name: Generate HTML accessibility results
        run: npm run docs-pa11y-html
        if: matrix.node == 12 && failure()

      - name: Upload accessibility results
        uses: actions/upload-artifact@v1
        if: matrix.node == 12 && failure()
        with:
          name: pa11y-ci-results
          path: .pa11y/

      - name: Percy Test
        uses: percy/snapshot-action@v0.1.0
        if: matrix.node == 12
        with:
          build-directory: "_gh_pages/"
          flags: "--snapshot-files ./*.html"
          verbose: true
        env:
          PERCY_TOKEN: "${{ secrets.PERCY_TOKEN }}"

      - name: Run Coveralls
        uses: coverallsapp/github-action@master
        if: matrix.node == 10
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          path-to-lcov: "./js/coverage/lcov.info"
