name: Tests
on: [push, pull_request]
env:
  CI: true

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [10, 12]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version
      - run: java -version

      - name: Set up npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.github/workflows/test.yml') }}
          restore-keys: |
            ${{ runner.OS }}-node-v${{ matrix.node }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.github/workflows/test.yml') }}
            ${{ runner.OS }}-node-v${{ matrix.node }}-

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run accessibility tests
        run: npm run docs-accessibility
        if: matrix.node == 12

      - name: Generate HTML accessibility results
        run: npm run docs-pa11y-html
        if: matrix.node == 12 && failure()

      - name: Upload accessibility results
        uses: actions/upload-artifact@v1
        if: matrix.node == 12 && failure()
        with:
          name: pa11y-ci-results
          path: .pa11y/

      - name: Run bundlesize
        run: npm run bundlesize
        if: matrix.node == 10
        env:
          BUNDLESIZE_GITHUB_TOKEN: "${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}"

      - name: Run BrowserStack tests
        run: npm run js-test-cloud
        if: matrix.node == 10 && github.repository == 'Orange-OpenSource/Orange-Boosted-Bootstrap' && github.event_name == 'push'
        env:
          BROWSER_STACK_ACCESS_KEY: "${{ secrets.BROWSER_STACK_ACCESS_KEY }}"
          BROWSER_STACK_USERNAME: "${{ secrets.BROWSER_STACK_USERNAME }}"

      - name: Percy Test
        uses: percy/snapshot-action@v0.1.0
        if: matrix.node == 12
        with:
          build-directory: "_gh_pages/"
          flags: "--snapshot-files ./*.html"
          verbose: true
        env:
          PERCY_TOKEN: "${{ secrets.PERCY_TOKEN }}"

      - name: Run Coveralls
        uses: coverallsapp/github-action@master
        if: matrix.node == 10
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          path-to-lcov: "./js/coverage/lcov.info"
